from datetime import datetime

from fusion import indexer, ledger


def test_golden_fixture_library(fixture_bucket):
    current = (fixture_bucket / "library" / "INDEX.md").read_bytes()
    generated = indexer.generate(fixture_bucket / "library", "library")
    assert generated.encode("utf-8") == current


def test_golden_fixture_activities(fixture_bucket):
    current = (fixture_bucket / "activities" / "INDEX.md").read_bytes()
    generated = indexer.generate(fixture_bucket / "activities", "activities")
    assert generated.encode("utf-8") == current


DOC = """---
title: {title}
type: note
aurora: {aurora}
---

## Summary

{summary}

---

Body.
"""


def _doc(path, title, summary, aurora="library"):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(DOC.format(title=title, aurora=aurora, summary=summary),
                    encoding="utf-8")


def test_ordering_root_first_archive_last(tmp_path):
    zone = tmp_path / "library"
    _doc(zone / "zeta.md", "Zeta", "Root doc.")
    _doc(zone / "beta" / "b.md", "B", "In beta.")
    _doc(zone / "archive" / "old.md", "Old", "Archived.", aurora="archive")
    _doc(zone / "alpha" / "a.md", "A", "In alpha.")
    out = indexer.generate(zone, "library")
    assert out == (
        "<!-- generated by fusion index — do not edit -->\n"
        "# Library Index\n"
        "\n"
        "## ./\n"
        "\n"
        "- [Zeta](zeta.md) — Root doc. (library)\n"
        "\n"
        "## alpha/\n"
        "\n"
        "- [A](alpha/a.md) — In alpha. (library)\n"
        "\n"
        "## beta/\n"
        "\n"
        "- [B](beta/b.md) — In beta. (library)\n"
        "\n"
        "## archive/\n"
        "\n"
        "- [Old](archive/old.md) — Archived. (archive)\n"
    )


def test_empty_zone(tmp_path):
    zone = tmp_path / "activities"
    zone.mkdir()
    assert indexer.generate(zone, "activities") == (
        "<!-- generated by fusion index — do not edit -->\n"
        "# Activities Index\n"
    )


def test_write_indexes_logs_only_changes(tmp_path):
    for zone in ("library", "activities"):
        (tmp_path / zone).mkdir()
    (tmp_path / "LEDGER.md").write_text("# Ledger\n", encoding="utf-8")
    _doc(tmp_path / "library" / "notes.md", "Notes", "Some notes.")

    results = indexer.write_indexes(tmp_path, actor="claude",
                                    at=datetime(2026, 7, 10, 10, 5))
    assert results == [
        {"zone": "library", "documents": 1, "changed": True},
        {"zone": "activities", "documents": 0, "changed": True},
    ]
    entries = ledger.read(tmp_path)
    assert [e.obj for e in entries] == [
        "library/ (1 document)", "activities/ (0 documents)",
    ]

    # second run: nothing changed, nothing logged
    results = indexer.write_indexes(tmp_path, actor="claude",
                                    at=datetime(2026, 7, 10, 10, 6))
    assert all(r["changed"] is False for r in results)
    assert len(ledger.read(tmp_path)) == 2


def test_dot_directory_filter_excludes_hidden_paths(tmp_path):
    """Verify that _zone_documents skips files in dot-prefixed directories."""
    zone = tmp_path / "library"
    _doc(zone / "visible.md", "Visible", "A real document.")
    _doc(zone / ".trash" / "ghost.md", "Ghost", "Should not appear in index.")
    out = indexer.generate(zone, "library")
    assert "visible.md" in out
    assert "Visible" in out
    assert "ghost" not in out.lower()
    assert "Ghost" not in out
