"""INDEX.md generation — two implementations, identical bytes (SPEC §8)."""
from __future__ import annotations

from datetime import datetime
from pathlib import Path

from . import ledger
from .document import read_document

MARKER = "<!-- generated by fusion index — do not edit -->"
INDEXED_ZONES: tuple[str, ...] = ("library", "activities")


def _section_key(section: str) -> tuple[int, str]:
    if section == "./":
        return (0, section)
    if section == "archive/" or section.startswith("archive/"):
        return (2, section)
    return (1, section)


def generate(zone_dir: Path, zone_name: str) -> str:
    sections: dict[str, list] = {}
    for path in sorted(zone_dir.rglob("*.md")):
        if path.name == "INDEX.md" or path.name.startswith("."):
            continue
        rel = path.relative_to(zone_dir)
        parent = rel.parent.as_posix()
        section = "./" if parent == "." else parent + "/"
        sections.setdefault(section, []).append((rel, read_document(path)))

    lines = [MARKER, f"# {zone_name.capitalize()} Index"]
    for section in sorted(sections, key=_section_key):
        lines += ["", f"## {section}", ""]
        for rel, doc in sorted(sections[section], key=lambda t: t[0].as_posix()):
            title = doc.title or rel.stem
            summary = doc.summary_line or ""
            aurora = doc.aurora or ""
            lines.append(f"- [{title}]({rel.as_posix()}) — {summary} ({aurora})")
    return "\n".join(lines) + "\n"


def write_indexes(
    bucket_root: Path,
    actor: str | None = None,
    at: datetime | None = None,
) -> list[dict]:
    results = []
    for zone in INDEXED_ZONES:
        zone_dir = bucket_root / zone
        if not zone_dir.is_dir():
            continue
        content = generate(zone_dir, zone)
        index_path = zone_dir / "INDEX.md"
        old = index_path.read_bytes() if index_path.exists() else None
        changed = old != content.encode("utf-8")
        if changed:
            index_path.write_text(content, encoding="utf-8")
        count = sum(
            1
            for p in zone_dir.rglob("*.md")
            if p.name != "INDEX.md" and not p.name.startswith(".")
        )
        if changed and actor:
            plural = "s" if count != 1 else ""
            ledger.append(bucket_root, actor, "indexed",
                          f"{zone}/ ({count} document{plural})", at=at)
        results.append({"zone": zone, "documents": count, "changed": changed})
    return results
