"""INDEX.md generation — two implementations, identical bytes (SPEC §8)."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from . import ledger
from .document import Document, read_document

MARKER = "<!-- generated by fusion index — do not edit -->"
INDEXED_ZONES: tuple[str, ...] = ("library", "activities")


def _section_key(section: str) -> tuple[int, str]:
    if section == "./":
        return (0, section)
    if section.startswith("archive/"):
        return (2, section)
    return (1, section)


def _zone_documents(zone_dir: Path) -> list[Path]:
    """Every document file in the zone — the single filter both the index
    content and the ledger's document count derive from."""
    return [
        p
        for p in sorted(zone_dir.rglob("*.md"))
        if p.name != "INDEX.md"
        and not any(part.startswith(".") for part in p.relative_to(zone_dir).parts)
    ]


def generate(zone_dir: Path, zone_name: str) -> str:
    sections: dict[str, list[tuple[Path, Document]]] = {}
    for path in _zone_documents(zone_dir):
        rel = path.relative_to(zone_dir)
        parent = rel.parent.as_posix()
        section = "./" if parent == "." else parent + "/"
        sections.setdefault(section, []).append((rel, read_document(path)))

    lines = [MARKER, f"# {zone_name.capitalize()} Index"]
    for section in sorted(sections, key=_section_key):
        lines += ["", f"## {section}", ""]
        for rel, doc in sorted(sections[section], key=lambda t: t[0].as_posix()):
            title = doc.title or rel.stem
            summary = doc.summary_line or ""
            aurora = doc.aurora or ""
            lines.append(f"- [{title}]({rel.as_posix()}) — {summary} ({aurora})")
    return "\n".join(lines) + "\n"


def write_indexes(
    bucket_root: Path,
    actor: str | None = None,
    at: datetime | None = None,
) -> list[dict[str, Any]]:
    results = []
    for zone in INDEXED_ZONES:
        zone_dir = bucket_root / zone
        if not zone_dir.is_dir():
            continue
        content = generate(zone_dir, zone)
        index_path = zone_dir / "INDEX.md"
        old = index_path.read_bytes() if index_path.exists() else None
        changed = old != content.encode("utf-8")
        if changed:
            index_path.write_text(content, encoding="utf-8", newline="\n")
        count = len(_zone_documents(zone_dir))
        if changed and actor:
            plural = "s" if count != 1 else ""
            ledger.append(
                bucket_root,
                actor,
                "indexed",
                f"{zone}/ ({count} document{plural})",
                at=at,
            )
        results.append({"zone": zone, "documents": count, "changed": changed})
    return results
